import { ChangeEvent, useEffect, useRef, useState } from 'react';
import { createRoot } from 'react-dom/client';
import { BarChart3, ChevronLeft, ChevronRight, CircleDollarSign, Download, Home, MoreHorizontal, Pencil, Plus, Receipt, Settings, Target, Trash2, Upload, X } from 'lucide-react';
import './styles.css';

type Category = '餐饮'|'交通'|'购物'|'娱乐'|'住房'|'生活'|'其他';
type Expense = { id:string; amount:number; title:string; category:Category; date:string; note:string; createdAt:string };
type Goal = { id:string; name:string; targetAmount:number; savedAmount:number; deadline:string; createdAt:string };
const categories:Category[]=['餐饮','交通','购物','娱乐','住房','生活','其他'];
const categoryIcons:Record<Category,string>={餐饮:'🍜',交通:'🚇',购物:'🛍️',娱乐:'🎬',住房:'🏠',生活:'🧺',其他:'•••'};
const categoryColors=['#151515','#6b6b66','#a3a39b','#c5c5bc','#deded6','#8d8d86','#b5b5ae'];
const today=()=>new Date().toISOString().slice(0,10);
const DB_NAME='my-ledger-db', DB_VERSION=1;
function openDB():Promise<IDBDatabase>{return new Promise((resolve,reject)=>{const request=indexedDB.open(DB_NAME,DB_VERSION);request.onupgradeneeded=()=>{const db=request.result;if(!db.objectStoreNames.contains('expenses'))db.createObjectStore('expenses',{keyPath:'id'});if(!db.objectStoreNames.contains('goals'))db.createObjectStore('goals',{keyPath:'id'})};request.onsuccess=()=>resolve(request.result);request.onerror=()=>reject(request.error)})}
async function dbAll<T>(store:string):Promise<T[]>{const db=await openDB();return new Promise((resolve,reject)=>{const req=db.transaction(store,'readonly').objectStore(store).getAll();req.onsuccess=()=>resolve(req.result as T[]);req.onerror=()=>reject(req.error)})}
async function dbReplace<T extends {id:string}>(store:string,items:T[]){const db=await openDB();return new Promise<void>((resolve,reject)=>{const tx=db.transaction(store,'readwrite'),os=tx.objectStore(store);os.clear();items.forEach(item=>os.put(item));tx.oncomplete=()=>resolve();tx.onerror=()=>reject(tx.error)})}
async function migrateLegacy(){const oldExpenses=localStorage.getItem('ledger-expenses'),oldGoals=localStorage.getItem('ledger-goals');if(oldExpenses){try{const current=await dbAll<Expense>('expenses');if(!current.length)await dbReplace('expenses',JSON.parse(oldExpenses))}catch{}}if(oldGoals){try{const current=await dbAll<Goal>('goals');if(!current.length)await dbReplace('goals',JSON.parse(oldGoals))}catch{}}}
const money=(n:number)=>`¥${n.toLocaleString('zh-CN',{minimumFractionDigits:2,maximumFractionDigits:2})}`;
const sum=(xs:Expense[])=>xs.reduce((a,x)=>a+x.amount,0);
const sameMonth=(date:string,month:string)=>date.slice(0,7)===month;
const monthLabel=(month:string)=>new Date(`${month}-01T00:00:00`).toLocaleDateString('zh-CN',{year:'numeric',month:'long'});
const shiftMonth=(month:string,delta:number)=>{const d=new Date(`${month}-01T00:00:00`);d.setMonth(d.getMonth()+delta);return d.toISOString().slice(0,7)};

function App(){
 const [expenses,setExpenses]=useState<Expense[]>([]); const [goals,setGoals]=useState<Goal[]>([]); const [storageReady,setStorageReady]=useState(false);
 const [tab,setTab]=useState<'home'|'add'|'stats'|'settings'>('home'); const [modal,setModal]=useState<Expense|null|false>(false); const [month,setMonth]=useState(today().slice(0,7));
 const persistExpenses=(v:Expense[])=>{setExpenses(v);void dbReplace('expenses',v)}; const persistGoals=(v:Goal[])=>{setGoals(v);void dbReplace('goals',v)};
 useEffect(()=>{void (async()=>{await migrateLegacy();const [e,g]=await Promise.all([dbAll<Expense>('expenses'),dbAll<Goal>('goals')]);setExpenses(e.sort((a,b)=>b.createdAt.localeCompare(a.createdAt)));setGoals(g);setStorageReady(true)})();if('serviceWorker' in navigator)navigator.serviceWorker.register('/sw.js').catch(()=>{});if(new URLSearchParams(location.search).get('action')==='add')setTab('add')},[]);
 const saveExpense=(e:Expense)=>{persistExpenses(modal?[...expenses.filter(x=>x.id!==e.id),e].sort((a,b)=>b.createdAt.localeCompare(a.createdAt)):[e,...expenses]);setModal(false);setTab('home')}; const openAdd=()=>{setModal(null);setTab('add')};
 if(!storageReady)return <div className="loading-screen"><div className="app-icon"><CircleDollarSign size={24}/></div><p>正在打开你的账本…</p></div>;
 return <div className="app-shell"><header className="topbar"><div className="brand"><div className="app-icon"><CircleDollarSign size={21}/></div><div><strong>我的记账</strong><span>轻松记录每一笔</span></div></div><button className="header-add" onClick={openAdd}><Plus size={18}/>记一笔</button></header><main className="main-content">{tab==='home'&&<HomePage expenses={expenses} goals={goals} onAdd={openAdd} onEdit={e=>setModal(e)} onDelete={e=>persistExpenses(expenses.filter(x=>x.id!==e.id))}/>} {tab==='add'&&<QuickAddPage expenses={expenses} onSave={saveExpense} onMore={()=>setModal(null)}/>} {tab==='stats'&&<StatsPage expenses={expenses} month={month} setMonth={setMonth}/>} {tab==='settings'&&<SettingsPage expenses={expenses} goals={goals} saveGoals={persistGoals} saveExpenses={persistExpenses}/>}</main><nav className="bottom-nav">{([['home','首页',Home],['add','记账',Plus],['stats','统计',BarChart3],['settings','设置',Settings]] as const).map(([key,label,Icon])=><button className={tab===key?'active':''} onClick={()=>key==='add'?openAdd():setTab(key)} key={key}><Icon size={21}/><span>{label}</span></button>)}</nav>{modal!==false&&<ExpenseModal initial={modal} close={()=>setModal(false)} save={saveExpense}/>}</div>
}

function HomePage({expenses,goals,onAdd,onEdit,onDelete}:{expenses:Expense[];goals:Goal[];onAdd:()=>void;onEdit:(e:Expense)=>void;onDelete:(e:Expense)=>void}){const d=today(),m=d.slice(0,7),todayItems=expenses.filter(e=>e.date===d),monthItems=expenses.filter(e=>sameMonth(e.date,m));return <section className="page"><div className="greeting"><div><p className="muted">{new Date().toLocaleDateString('zh-CN',{weekday:'long',month:'long',day:'numeric'})}</p><h1>今天也要记得<br/><em>照顾好钱包。</em></h1></div><div className="date-dot">{new Date().getDate()}</div></div><section className="balance-card"><span>今日消费</span><strong>{money(sum(todayItems))}</strong><div className="balance-foot"><small>本月已消费 {money(sum(monthItems))}</small><button onClick={onAdd}><Plus size={16}/>快速记账</button></div></section><div className="quick-stats"><div><span>本月消费</span><strong>{money(sum(monthItems))}</strong></div><div><span>本月笔数</span><strong>{monthItems.length}<small> 笔</small></strong></div></div><div className="section-title"><h2>最近账单</h2><span>{expenses.length} 笔</span></div>{expenses.length===0?<Empty onAdd={onAdd}/>:<div className="bill-list">{expenses.slice(0,7).map(e=><Bill key={e.id} item={e} onEdit={()=>onEdit(e)} onDelete={()=>onDelete(e)}/>)}</div>}{goals[0]&&<GoalPreview goal={goals[0]}/>}</section>}
function Bill({item:e,onEdit,onDelete}:{item:Expense;onEdit:()=>void;onDelete:()=>void}){return <div className="bill"><div className="bill-icon">{categoryIcons[e.category]}</div><div className="bill-copy"><strong>{e.title}</strong><span>{e.category} · {e.date} {e.createdAt.slice(11,16)}</span></div><b>-{money(e.amount)}</b><div className="bill-actions"><button onClick={onEdit}><Pencil size={15}/></button><button onClick={onDelete}><Trash2 size={15}/></button></div></div>}
function Empty({onAdd}:{onAdd:()=>void}){return <div className="empty"><Receipt size={28}/><p>还没有账单记录</p><button className="link-button" onClick={onAdd}>记录第一笔</button></div>}
function GoalPreview({goal:g}:{goal:Goal}){const pct=Math.min(100,Math.round(g.savedAmount/g.targetAmount*100));return <div className="goal-preview"><div><span>存钱目标</span><strong>{g.name}</strong></div><b>{pct}%</b><div className="progress"><i style={{width:`${pct}%`}}/></div></div>}

function QuickAddPage({expenses,onSave,onMore}:{expenses:Expense[];onSave:(e:Expense)=>void;onMore:()=>void}){const recent=[...new Set([...expenses].sort((a,b)=>b.createdAt.localeCompare(a.createdAt)).map(e=>e.category))];const ordered=[...recent,...categories.filter(c=>!recent.includes(c))];const [amount,setAmount]=useState('');const [cat,setCat]=useState<Category>(ordered[0]||'餐饮');const [title,setTitle]=useState('');const [note,setNote]=useState('');const save=()=>{if(Number(amount)<=0)return;onSave({id:crypto.randomUUID(),amount:Number(amount),title:title.trim()||cat,category:cat,date:today(),note,createdAt:new Date().toISOString()})};return <section className="page quick-page"><div className="page-heading"><div><p className="muted">快速记账</p><h2>花了多少？</h2></div><button className="close-page" onClick={()=>{setAmount('');setTitle('');setNote('')}}>清空</button></div><div className="amount-input"><span>¥</span><input type="number" min="0" inputMode="decimal" autoFocus placeholder="0.00" value={amount} onChange={e=>setAmount(e.target.value)}/></div><p className="field-label">选择分类</p><div className="category-pills">{ordered.map(c=><button className={cat===c?'selected':''} key={c} onClick={()=>setCat(c)}><span>{categoryIcons[c]}</span>{c}</button>)}</div><label className="form-label">消费内容（可选）<input placeholder="例如：午餐、地铁" value={title} onChange={e=>setTitle(e.target.value)}/></label><label className="form-label">备注（可选）<input placeholder="添加一点说明" value={note} onChange={e=>setNote(e.target.value)}/></label><button className="primary save-button" onClick={save} disabled={Number(amount)<=0}><Plus size={19}/>保存今天的消费</button><button className="more-button" onClick={onMore}><MoreHorizontal size={18}/>更多选项（日期等）</button></section>}

function StatsPage({expenses,month,setMonth}:{expenses:Expense[];month:string;setMonth:(m:string)=>void}){const list=expenses.filter(e=>sameMonth(e.date,month));const byCat=categories.map((c,i)=>({c,n:sum(list.filter(e=>e.category===c)),color:categoryColors[i]})).filter(x=>x.n);const days=Array.from({length:7},(_,i)=>{const d=new Date(`${month}-01T00:00:00`);d.setDate(i+1);const key=d.toISOString().slice(0,10);return {label:`${i+1}`,value:sum(list.filter(e=>e.date===key))}});const max=Math.max(...days.map(d=>d.value),1);const gradient=donutGradient(byCat,sum(list));return <section className="page"><div className="page-heading"><div><p className="muted">消费分析</p><h2>统计</h2></div><div className="month-switch"><button onClick={()=>setMonth(shiftMonth(month,-1))}><ChevronLeft size={19}/></button><span>{monthLabel(month)}</span><button disabled={month>=today().slice(0,7)} onClick={()=>setMonth(shiftMonth(month,1))}><ChevronRight size={19}/></button></div></div><div className="stats-total"><span>本月总消费</span><strong>{money(sum(list))}</strong><small>{list.length} 笔账单</small></div><div className="chart-card"><div className="chart-title"><h3>消费趋势</h3><span>前 7 天</span></div><div className="line-chart"><div className="chart-grid"><i/><i/><i/><i/></div><svg viewBox="0 0 350 120" preserveAspectRatio="none"><polyline points={days.map((d,i)=>`${i*58+6},${114-(d.value/max*95)}`).join(' ')} fill="none" stroke="#151515" strokeWidth="3" strokeLinecap="round" strokeLinejoin="round"/></svg><div className="chart-labels">{days.map(d=><span key={d.label}>{d.label}日</span>)}</div></div></div><div className="chart-card"><div className="chart-title"><h3>分类占比</h3><span>{monthLabel(month)}</span></div>{byCat.length?<div className="donut-row"><div className="donut" style={{background:gradient}}><div><strong>{money(sum(list))}</strong><small>总消费</small></div></div><div className="legend">{byCat.map(x=><div key={x.c}><i style={{background:x.color}}/><span>{categoryIcons[x.c]} {x.c}</span><b>{Math.round(x.n/sum(list)*100)}%</b></div>)}</div></div>:<div className="empty mini-empty"><BarChart3 size={24}/><p>这个月还没有消费</p></div>}</div></section>}
function donutGradient(xs:{n:number;color:string}[],total:number){if(!total)return 'conic-gradient(#e8e8e3 0deg 360deg)';let start=0;return `conic-gradient(${xs.map(x=>{const end=start+x.n/total*360;const part=`${x.color} ${start}deg ${end}deg`;start=end;return part}).join(',')})`}

function SettingsPage({expenses,goals,saveGoals,saveExpenses}:{expenses:Expense[];goals:Goal[];saveGoals:(g:Goal[])=>void;saveExpenses:(e:Expense[])=>void}){const file=useRef<HTMLInputElement>(null);const [goalName,setGoalName]=useState(goals[0]?.name||'');const [goalTarget,setGoalTarget]=useState(goals[0]?.targetAmount?.toString()||'');const [goalSaved,setGoalSaved]=useState(goals[0]?.savedAmount?.toString()||'');const download=(content:string,name:string,type:string)=>{const a=document.createElement('a');a.href=URL.createObjectURL(new Blob([content],{type}));a.download=name;a.click();URL.revokeObjectURL(a.href)};const csv=()=>download(['日期,内容,分类,金额,备注',...expenses.map(e=>`${e.date},${e.title},${e.category},${e.amount},${e.note}`)].join('\n'),'我的记账.csv','text/csv;charset=utf-8');const importData=(ev:ChangeEvent<HTMLInputElement>)=>{const f=ev.target.files?.[0];if(!f)return;const reader=new FileReader();reader.onload=()=>{try{const data=JSON.parse(String(reader.result));if(Array.isArray(data.expenses))saveExpenses(data.expenses);if(Array.isArray(data.goals))saveGoals(data.goals);alert('数据恢复成功')}catch{alert('文件格式不正确')}};reader.readAsText(f)};const saveGoal=()=>{if(!goalName||Number(goalTarget)<=0)return;saveGoals([{id:goals[0]?.id||crypto.randomUUID(),name:goalName,targetAmount:Number(goalTarget),savedAmount:Number(goalSaved)||0,deadline:goals[0]?.deadline||'',createdAt:goals[0]?.createdAt||new Date().toISOString()}]);alert('目标已保存')};return <section className="page settings-page"><div className="page-heading"><div><p className="muted">个人偏好</p><h2>设置</h2></div><Settings size={24}/></div><div className="setting-group"><h3>数据管理</h3><button onClick={()=>download(JSON.stringify({expenses,goals},null,2),'我的记账备份.json','application/json')}><Download size={18}/>导出 JSON <span>完整备份</span></button><button onClick={csv}><Download size={18}/>导出 CSV <span>表格格式</span></button><button onClick={()=>file.current?.click()}><Upload size={18}/>恢复数据 <span>导入 JSON 备份</span></button><input ref={file} type="file" accept="application/json" hidden onChange={importData}/></div><div className="setting-group"><h3>存钱目标</h3><label className="form-label">目标名称<input value={goalName} placeholder="例如：旅行基金" onChange={e=>setGoalName(e.target.value)}/></label><div className="two-fields"><label className="form-label">目标金额<input type="number" min="0" value={goalTarget} onChange={e=>setGoalTarget(e.target.value)}/></label><label className="form-label">已存金额<input type="number" min="0" value={goalSaved} onChange={e=>setGoalSaved(e.target.value)}/></label></div><button className="primary setting-save" onClick={saveGoal}><Target size={17}/>保存目标</button></div><div className="about"><div className="app-icon small"><CircleDollarSign size={18}/></div><div><strong>我的记账</strong><span>离线优先 · 数据只保存在本机</span></div></div></section>}

function ExpenseModal({initial,close,save}:{initial:Expense|null;close:()=>void;save:(e:Expense)=>void}){const [f,setF]=useState({title:initial?.title||'',amount:initial?.amount?.toString()||'',category:initial?.category||'餐饮' as Category,date:initial?.date||today(),note:initial?.note||''});const submit=()=>{if(!f.title.trim()||Number(f.amount)<=0)return;save({id:initial?.id||crypto.randomUUID(),amount:Number(f.amount),title:f.title.trim(),category:f.category,date:f.date,note:f.note,createdAt:initial?.createdAt||new Date().toISOString()})};return <div className="modal-layer"><div className="modal"><div className="modal-head"><h2>{initial?'编辑账单':'更多记账'}</h2><button onClick={close}><X/></button></div><label className="form-label">消费内容<input autoFocus value={f.title} placeholder="例如：午餐" onChange={e=>setF({...f,title:e.target.value})}/></label><label className="form-label">金额<input type="number" min="0.01" inputMode="decimal" value={f.amount} placeholder="0.00" onChange={e=>setF({...f,amount:e.target.value})}/></label><p className="field-label">分类</p><div className="modal-cats">{categories.map(c=><button className={f.category===c?'selected':''} onClick={()=>setF({...f,category:c})} key={c}>{categoryIcons[c]} {c}</button>)}</div><label className="form-label">日期<input type="date" value={f.date} onChange={e=>setF({...f,date:e.target.value})}/></label><label className="form-label">备注<input value={f.note} placeholder="可选" onChange={e=>setF({...f,note:e.target.value})}/></label><button className="primary save-button" onClick={submit}>保存记录</button></div></div>}

createRoot(document.getElementById('root')!).render(<App/>);
